import type { LocationData } from "@/components/locations/LocationPage";

export const CITIES: Record<string, LocationData> = {
  krakow: {
    slug: "krakow",
    city: "Kraków",
    cityGenitive: "Krakowa",
    cityIn: "Krakowie",
    voivodeship: "Małopolska",
    postalCode: "31-010",
    isHQ: true,
    geo: { lat: 50.062, lng: 19.9366, bbox: [19.7, 49.96, 20.18, 50.18] },
    population: "780 tys.",
    industries: ["motoryzacja", "energetyka", "spożywcza", "chemia", "IT/biurowce"],
    nearbyClients: ["PGE GiEK", "Cefarm", "ZF Friedrichshafen Kraków", "Kraków Airport"],
    zipCodesServed: ["30-XXX", "31-XXX", "32-XXX", "33-XXX"],
    drivingDistance: "Siedziba w centrum Krakowa. Promień 80 km — bezpłatny dojazd.",
  },
  warszawa: {
    slug: "warszawa",
    city: "Warszawa",
    cityGenitive: "Warszawy",
    cityIn: "Warszawie",
    voivodeship: "Mazowieckie",
    geo: { lat: 52.2297, lng: 21.0122, bbox: [20.85, 52.1, 21.27, 52.37] },
    population: "1,86 mln",
    industries: ["energetyka", "biurowce klasy A", "spożywcza", "logistyka", "farmaceutyczna"],
    nearbyClients: ["Skanska", "PGE", "Polmlek", "Cefarm"],
    zipCodesServed: ["00-XXX", "01-XXX", "02-XXX", "03-XXX", "04-XXX"],
    drivingDistance: "Audytorzy z Warszawy w 2h. Bezpłatny dojazd w promieniu 80 km.",
  },
  wroclaw: {
    slug: "wroclaw",
    city: "Wrocław",
    cityGenitive: "Wrocławia",
    cityIn: "Wrocławiu",
    voivodeship: "Dolnośląskie",
    geo: { lat: 51.1079, lng: 17.0385, bbox: [16.84, 51.0, 17.2, 51.2] },
    population: "672 tys.",
    industries: ["motoryzacja", "AGD", "elektronika", "chemia", "logistyka"],
    nearbyClients: ["BSH SGD Wrocław", "Volkswagen Polkowice", "LG Display"],
    zipCodesServed: ["50-XXX", "51-XXX", "52-XXX", "53-XXX"],
    drivingDistance: "Audytorzy w 3h. Bezpłatny dojazd w promieniu 80 km.",
  },
  lodz: {
    slug: "lodz",
    city: "Łódź",
    cityGenitive: "Łodzi",
    cityIn: "Łodzi",
    voivodeship: "Łódzkie",
    geo: { lat: 51.7592, lng: 19.456, bbox: [19.27, 51.65, 19.65, 51.85] },
    population: "664 tys.",
    industries: ["AGD", "tekstylia", "chemia", "logistyka", "spożywcza"],
    nearbyClients: ["Polmlek", "Dell Łódź", "Gillette"],
    zipCodesServed: ["90-XXX", "91-XXX", "92-XXX", "93-XXX", "94-XXX"],
    drivingDistance: "Łódź w 2h od siedziby. Bezpłatny dojazd w promieniu 80 km.",
  },
  katowice: {
    slug: "katowice",
    city: "Katowice",
    cityGenitive: "Katowic",
    cityIn: "Katowicach",
    voivodeship: "Śląskie",
    geo: { lat: 50.2649, lng: 19.0238, bbox: [18.86, 50.18, 19.18, 50.32] },
    population: "286 tys.",
    industries: ["górnictwo", "metalurgia", "energetyka", "chemia", "motoryzacja"],
    nearbyClients: ["Tauron", "Grupa Azoty", "ArcelorMittal", "Fiat"],
    zipCodesServed: ["40-XXX", "41-XXX", "42-XXX", "43-XXX"],
    drivingDistance: "Najbliższe sąsiedztwo. Audytorzy w 1.5h. Cały Górny Śląsk.",
  },
};

export const CITY_SLUGS = Object.keys(CITIES);
